'use client'

import { supabase } from "@/lib/supabase-browser"
import { useEffect, useState } from "react"

import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"
import {
Card,
CardHeader,
CardTitle,
CardContent,
CardDescription
} from "@/components/ui/card"

import { Badge } from "@/components/ui/badge"

export default function CreatePage(){

const [userId,setUserId] = useState<string | null>(null)
const [automationEnabled,setAutomationEnabled] = useState(false)
const [youtubeConnected,setYoutubeConnected] = useState(false)

const [videos,setVideos] = useState<any[]>([])
const [loading,setLoading] = useState(true)

useEffect(()=>{

async function init(){

const {data} = await supabase.auth.getUser()
if(!data.user) return

setUserId(data.user.id)

const {data:profile} = await supabase
.from("users")
.select("automation_enabled")
.eq("id",data.user.id)
.maybeSingle()

setAutomationEnabled(profile?.automation_enabled ?? false)

const {data:yt} = await supabase
.from("youtube_accounts")
.select("id")
.eq("user_id",data.user.id)
.maybeSingle()

setYoutubeConnected(!!yt)

await loadVideos(data.user.id)

}

init()

},[])

useEffect(()=>{

if(!userId) return

const interval = setInterval(()=>{
loadVideos(userId)
},5000)

return ()=>clearInterval(interval)

},[userId])

async function loadVideos(uid:string){

const {data} = await supabase
.from("generated_videos")
.select("*")
.eq("user_id",uid)
.order("created_at",{ascending:false})
.limit(20)

setVideos(data || [])
setLoading(false)

}

async function toggleAutomation(){

if(!userId) return

const newState = !automationEnabled

const {data,error} = await supabase
.from("users")
.update({
automation_enabled:newState
})
.eq("id",userId)
.select()
.single()

if(!error && data){
setAutomationEnabled(data.automation_enabled)
}

}

function getStatusColor(status:string){

if(status==="queued") return "bg-gray-500 text-white"

if(status==="rendering") return "bg-blue-600 text-white"

if(status==="uploading") return "bg-yellow-600 text-white"

if(status==="published") return "bg-green-600 text-white"

if(status==="failed") return "bg-red-600 text-white"

return "bg-gray-400 text-white"

}

function getStatusMessage(status:string){

if(status==="queued") return "Waiting for worker"

if(status==="rendering") return "Rendering video..."

if(status==="uploading") return "Uploading to YouTube..."

if(status==="published") return "Video published successfully"

if(status==="failed") return "Video generation failed"

return ""

}

return(

<div className="space-y-8">

<PageHeader
title="Automation Dashboard"
description="Your AI video system"
/>

<div className="grid lg:grid-cols-2 gap-8">

<Card>

<CardHeader>
<CardTitle>Automation Control</CardTitle>
<CardDescription>
Enable automatic video generation
</CardDescription>
</CardHeader>

<CardContent className="space-y-4">

<Button
onClick={toggleAutomation}
className={
automationEnabled
? "bg-green-600 hover:bg-green-700 text-white"
: "bg-gray-600 hover:bg-gray-700 text-white"
}
>

{automationEnabled
? "Automation Enabled"
: "Enable Automation"}

</Button>

</CardContent>

</Card>

<Card>

<CardHeader>
<CardTitle>YouTube Connection</CardTitle>
<CardDescription>
Connect your channel once
</CardDescription>
</CardHeader>

<CardContent>

{youtubeConnected ? (

<Badge className="bg-green-600 text-white">
YouTube Connected
</Badge>

) : (

<Button
onClick={()=>window.location.href="/api/youtube/connect"}
variant="outline"
>
Connect YouTube
</Button>

)}

</CardContent>

</Card>

</div>

<Card>

<CardHeader>
<CardTitle>Recent Videos</CardTitle>
<CardDescription>
Videos generated by the system
</CardDescription>
</CardHeader>

<CardContent className="space-y-6">

{loading && <p>Loading videos...</p>}

{videos.map(video=>(

<Card key={video.id}>

<CardHeader className="flex flex-row items-center justify-between">

<div>
<CardTitle>{video.topic}</CardTitle>
<p className="text-xs text-muted-foreground">
{getStatusMessage(video.status)}
</p>
</div>

<Badge className={getStatusColor(video.status)}>
{video.status}
</Badge>

</CardHeader>

<CardContent className="space-y-4">

{video.video_url && (

<video
src={video.video_url}
controls
className="w-full rounded-lg"
/>

)}

{video.script && (

<div className="text-xs bg-muted p-4 rounded-lg">
{video.script}
</div>

)}

{video.youtube_url && (

<a
href={video.youtube_url}
target="_blank"
className="text-blue-600 underline text-sm"
>
View on YouTube
</a>

)}

</CardContent>

</Card>

))}

{videos.length===0 && !loading && (

<p className="text-muted-foreground">
No videos generated yet.
</p>

)}

</CardContent>

</Card>

</div>

)

}